name: ValentCity
version: '1.2.5'
main: me.dantesys.valentCity.ValentCity
api-version: '1.21'
authors: [ Dantesys ]
description: Um plugin usando no servidor valent city
commands:
  kitrq:
    description: Recebe as reliquias
    usage: /<command> <target>