name: ValentCity
version: '1.11.0'
main: me.dantesys.valentCity.ValentCity
api-version: '1.21'
authors: [ Dantesys ]
description: Um plugin usando no servidor valent city
commands:
  reliquia:
    description: Recebe as reliquias
    usage: /<command> <target> <reliquias> espada, spy, foice, totem, tridente, vento, arco, fazendeiro, crossbow, mineiro, domador, mago e all (para todas)
    permission: reliquias.use
    permission-message: Você não tem permissão
  livro:
    description: Recebe o livro
    usage: /<command> <target>
    permission: reliquias.livro
    permission-message: Você não tem permissão
permissions:
  relics.livro:
    description: Permiter pegar o livro
    default: true
  relics.use:
    description: Permiter pegar as reliquias
    default: op
  relics.*:
    description: Valent City Permissões
    default: op
    children:
      relics.use: true