name: ValentCity
version: '2.14.1'
main: me.dantesys.valentCity.ValentCity
api-version: '1.21.1'
authors: [ Dantesys ]
description: Um plugin usando no servidor valent city
commands:
  rlist:
    description: Para gerenciar os registros das reliquias
    usage: /<command> [list|registrar]
    permission: reliquas.registro
    permission-message: Você não tem permissão
  reliquia:
    description: Recebe as reliquias
    usage: /<command> <target> <reliquias>
    permission: reliquias.use
    permission-message: Você não tem permissão
  livro:
    description: Recebe o livro
    usage: /<command> <target>
    permission: reliquias.livro
    permission-message: Você não tem permissão
permissions:
  reliquias.registro:
    description: Ver registros
    default: op
  reliquias.livro:
    description: Permiter pegar o livro
    default: not op
  reliquias.use:
    description: Permiter pegar as reliquias
    default: op